### ISSUE TITLE
npm run compare throws error deep within autocannon-compare dependency chain

### ISSUE THREAD

**Issue by Akkuma** [fastify/benchmarks#101]
```
(node:82791) UnhandledPromiseRejectionWarning: TypeError: gammaCollection.betaln is not a function
    at beta (/Users/omni/Documents/git/fastify-benchmarks/node_modules/mathfn/functions/beta.js:43:37)
    at Object.incBeta (/Users/omni/Documents/git/fastify-benchmarks/node_modules/mathfn/functions/beta.js:133:35)
    at StudenttDistribution.cdf (/Users/omni/Documents/git/fastify-benchmarks/node_modules/distributions/distributions/studentt.js:32:17)
    at StudentT.AbstactStudentT.pValue (/Users/omni/Documents/git/fastify-benchmarks/node_modules/ttest/hypothesis/abstact.js:22:32)
    at StudentT.AbstactStudentT.valid (/Users/omni/Documents/git/fastify-benchmarks/node_modules/ttest/hypothesis/abstact.js:42:15)
    at calculate (/Users/omni/Documents/git/fastify-benchmarks/node_modules/autocannon-compare/compare.js:39:17)
    at compare (/Users/omni/Documents/git/fastify-benchmarks/node_modules/autocannon-compare/compare.js:12:15)
    at module.exports.compare (/Users/omni/Documents/git/fastify-benchmarks/lib/autocannon.js:47:16)
    at inquirer.prompt.then (/Users/omni/Documents/git/fastify-benchmarks/benchmark-compare.js:126:22)
```

**Comment by Eomm** [comment]
How did you get this error?
```
git clone ..
npm install
npm run compare
```
or something else?

**Comment by muturgan** [comment]
my steps:
```
git clone ..
npm install
npm run compare
```
result:
```
(node:9740) UnhandledPromiseRejectionWarning: TypeError: gammaCollection.betaln is not a function
    at beta (/home/tester/Desktop/ttt/benchmarks/node_modules/mathfn/functions/beta.js:43:37)
    at Object.incBeta (/home/tester/Desktop/ttt/benchmarks/node_modules/mathfn/functions/beta.js:133
:35)
    at StudenttDistribution.cdf (/home/tester/Desktop/ttt/benchmarks/node_modules/distributions/distributions/studentt.js:32:17)
    at StudentT.AbstactStudentT.pValue (/home/tester/Desktop/ttt/benchmarks/node_modules/ttest/hypothesis/abstact.js:22:32)
    at StudentT.AbstactStudentT.valid (/home/tester/Desktop/ttt/benchmarks/node_modules/ttest/hypothesis/abstact.js:42:15)
    at calculate (/home/tester/Desktop/ttt/benchmarks/node_modules/autocannon-compare/compare.js:39:17)
    at compare (/home/tester/Desktop/ttt/benchmarks/node_modules/autocannon-compare/compare.js:12:15)
    at module.exports.compare (/home/tester/Desktop/ttt/benchmarks/lib/autocannon.js:47:16)
    at inquirer.prompt.then (/home/tester/Desktop/ttt/benchmarks/benchmark-compare.js:126:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

my enviroment:
ubuntu 19.04
node 10.16.3
npm 6.11.2
yarn 1.17.3

**Comment by muturgan** [comment]
btw updating autocannon-compare to v.0.4.0 fix this problem
really glad that this project is under maintaining
