### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by zekth** [fastify/benchmarks#120]
I'm concerned about certain lines of logs in the benchmarks which could lead to potential false results:

```
// egg.js
2020-08-01T00:47:46.2549900Z 2020-08-01 00:47:46,237 ERROR 2839 [-/undefined/-/3ms GET /] nodejs.EPIPEError: write EPIPE
2020-08-01T00:47:46.2550242Z     at afterWriteDispatched (internal/stream_base_commons.js:154:25)
2020-08-01T00:47:46.2550525Z     at writevGeneric (internal/stream_base_commons.js:137:3)
2020-08-01T00:47:46.2550797Z     at Socket._writeGeneric (net.js:784:11)
2020-08-01T00:47:46.2551057Z     at Socket._writev (net.js:793:8)
2020-08-01T00:47:46.2551293Z     at doWrite (_stream_writable.js:401:12)
2020-08-01T00:47:46.2551543Z     at clearBuffer (_stream_writable.js:519:5)
2020-08-01T00:47:46.2551790Z     at Socket.Writable.uncork (_stream_writable.js:338:7)
2020-08-01T00:47:46.2552070Z     at ServerResponse._flushOutput (_http_outgoing.js:854:10)
2020-08-01T00:47:46.2552330Z     at ServerResponse._flush (_http_outgoing.js:823:22)
2020-08-01T00:47:46.2552541Z     at ServerResponse.assignSocket (_http_server.js:219:8)
2020-08-01T00:47:46.2552766Z errno: "EPIPE"
2020-08-01T00:47:46.2553000Z code: "EPIPE"
2020-08-01T00:47:46.2553237Z syscall: "write"
2020-08-01T00:47:46.2553458Z headerSent: true
2020-08-01T00:47:46.2553677Z name: "EPIPEError"
2020-08-01T00:47:46.2553882Z pid: 2839
2020-08-01T00:47:46.2554301Z hostname: fv-az54
```

```
// express with route
2020-08-01T00:49:47.7387707Z (node:2957) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

```
// trek routeur
2020-08-01T01:20:30.2061204Z   HttpError: write ECONNRESET
2020-08-01T01:20:30.2061702Z       at Array.onError (/home/runner/work/benchmarks/benchmarks/node_modules/trek-engine/lib/engine.js:54:15)
2020-08-01T01:20:30.2062194Z       at listener (/home/runner/work/benchmarks/benchmarks/node_modules/on-finished/index.js:169:15)
2020-08-01T01:20:30.2062680Z       at onFinish (/home/runner/work/benchmarks/benchmarks/node_modules/on-finished/index.js:100:5)
2020-08-01T01:20:30.2063161Z       at callback (/home/runner/work/benchmarks/benchmarks/node_modules/ee-first/index.js:55:10)
2020-08-01T01:20:30.2063648Z       at Socket.onevent (/home/runner/work/benchmarks/benchmarks/node_modules/ee-first/index.js:93:5)
2020-08-01T01:20:30.2063841Z       at Socket.emit (events.js:327:22)
2020-08-01T01:20:30.2064054Z       at errorOrDestroy (internal/streams/destroy.js:108:12)
2020-08-01T01:20:30.2064265Z       at onwriteError (_stream_writable.js:418:5)
2020-08-01T01:20:30.2064464Z       at onwrite (_stream_writable.js:445:5)
2020-08-01T01:20:30.2064653Z       at internal/streams/destroy.js:50:7
```

Mention @Eomm

**Comment by RafaelGSS** [comment]
The last two execution was succeded. Shall we close it?

**Comment by mcollina** [comment]
closed!
