### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by mohd-akram** [fastify/benchmarks#327]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

1.0.0

### Node.js version

20.11.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.2

### Description

The tool fails to run.

### Steps to Reproduce

```shell
$ benchmark
node:internal/modules/cjs/loader:598
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/mohamed/.local/lib/node_modules/fastify-benchmarks/node_modules/rayo/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at /Users/mohamed/.local/lib/node_modules/fastify-benchmarks/lib/packages.js:46:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/mohamed/.local/lib/node_modules/fastify-benchmarks/lib/packages.js:43:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by mcollina** [comment]
Ah I don't think we ever released a working version of the module, just clone the repository and run it.

**Comment by jainChetan81** [comment]
going through the same issue while running local tbh
I cloned the repo, then `npm install` and `npm i -g fastify-benchmarks` then `benchmark compare -t` or `-s`, all of them give the same results
Is there any way that I can run this on local or even better on CI, as I want to modify test cases and run them on my account
